#### RUN CONFIGS ################################################################################
run_type: train # options: train, test, forward_infer

#### FILE CONFIGS ################################################################################
path_to_image_folder: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tiny_depadded_no_marks'
path_to_save_epochs: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tensorflow_setup/trial_run'
path_to_load_model: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tensorflow_setup/trial_run/epoch-2.pth'
path_to_copy_infer_images: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tensorflow_setup/trial_infer'

#### MODEL CONFIGS ################################################################################
model: 'gmtNet'
num_classes: 9
p_dropout: .6
train_proportion: .8
batch_size: 32
neurons_reducer_block: 256
adam_learning_rate: .0008
num_epochs: 10

#### METADATA CONFIGS ################################################################################
include_metadata: True
metadata_csv: 'mini_extended.csv'
meta_image_name_column: 'Image' # name of column in csv that references the image titles (NOTE: file type at end assumed for all rows (e.g. .jpg/.png))
comb_method: 'metanet' # options: None, metanet, metablock, concat
comb_config: (32, 8) # tuple for MetaNet (n_middle_channels, n_out_channels), integer for all other cases 
meta_columns: ['Area Filled mm 2',
 'Area Holes mm 2',
 'Area Holes Area Filled Ratio',
 'Area Skeleton mm 2',
 'Circularity Filled',
 'Circularity Holes',
 'Centroid X mm',
 'Centroid Y mm',
 'Coeff of variation pixel intensity',
 'Convex Area mm 2',
 'Convex Perimeter mm',
 'Centroid Distance mm',
 'Centroid Distance Area Holes Ratio',
 'Elongation',
 'Eccentricity',
 'Extent',
 'Feret Area Filled Ratio',
 'Feret Area Holes Ratio',
 'Fractal Dimension',
 'Height mm',
 'Integrated Density',
 'Intensity Max',
 'Intensity Min',
 'Intensity Mean',
 'Intensity Range',
 'Intensity Std Dev',
 'Intensity Skew',
 'Intensity Kurtosis',
 'Intensity SR',
 'Orientation deg',
 'Perim Filled Feret Ratio',
 'Perim Filled Area Filled Ratio',
 'Perim Filled Area Holes Ratio',
 'Perim Filled Major Axis Ratio',
 'Perimeter Filled mm',
 'Perimeter Holes mm',
 'Mean Position',
 'Hist Cum Slope',
 'Hist Cum 25',
 'Hist Cum 50',
 'Hist Cum 75',
 'Horiz Symmetry',
 'Vert Symmetry',
 'Weighted Centroid X',
 'Weighted Centroid Y',
 'Weighted Moment Central 00',
 'Weighted Moment Central 01',
 'Weighted Moment Central 02',
 'Weighted Moment Central 10',
 'Weighted Moment Central 11',
 'Weighted Moment Central 12',
 'Weighted Moment Central 20',
 'Weighted Moment Central 21',
 'Weighted Moment Central 22',
 'Width mm',
 'ECD mm',
 'Feret Diam mm',
 'Temp deg C',
 'Salinity',
 'Rho kg m-3',
 'Fluor',
 'Major Axis Len mm',
 'Minor Axis Len mm',
 'Pressure dbar']

 # TO DO: ADD DATALOADER CONFIGS (NUM_WORKERS, PIN_MEMORY)