#### RUN CONFIGS ################################################################################
run_type: train # options: train, forward_infer
path_to_image_folder: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tiny_depadded_no_marks'

#### DATALOADER CONFIGS ################################################################################
batch_size: 64
num_workers: 4
pin_memory: True

#### TRAIN CONFIGS ################################################################################
trial_id: 90026

### DATALOADER CONFIGS ###
image_norm_csv: None # set to None to use default arguments for each model
train_proportion: .8
train_test_split_seed: 42

### MODEL CONFIGS ###
model: 'vit'
p_dropout: .6
neurons_reducer_block: 256 
adam_learning_rate: .0008 
num_epochs: 50

### EARLY STOPPING CONFIGS ###
early_stopper: True
es_patience: 1
es_min_delta: 0

#### FORWARD INFERENCE CONFIGS ################################################################################
path_to_copy_infer_images: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tensorflow_setup/trial_infer'
path_to_load_model: '/mnt/c/Users/Julia/Documents/NIWC/Planktonic/tensorflow_setup/zooml_julia/epoch-5.pth'
# NOTE: IF YOU WANT TO INCLUDE METADATA, FILL OUT include_metadata, metadata_csv, AND meta_image_column BELOW. 

#### METADATA CONFIGS ################################################################################
include_metadata: True
metadata_csv: 'mini_extended.csv'
meta_image_name_column: 'Image' # name of column in csv that references the image titles (NOTE: file type at end assumed for all rows (e.g. .jpg/.png))
comb_method: 'metanet' # options: None, metanet, metablock, concat
comb_config: (32, 12, 2, 1) 
# two values for MetaBlock (n_feature_maps, hyper_parameter [32 before])
# NOTE: SHOULD BE FACTOR OF n_feat_conv (effNet 1280, gmtNet 512, VIT 768) * BATCH_SIZE / n_feature_maps / hyper_parameter 
# three values for MetaNet (n_middle_channels, n_out_channels/feature_maps, hyper_parameter1, hyper_parameter2 [8, 8 before])
# NOTE: SHOULD ALL MULTIPLY TO n_feat_conv * batch_size 
# integer for Concat (value will be ignored, can be anything)


meta_columns: ['Area Filled mm 2',
 'Area Holes mm 2',
 'Area Holes Area Filled Ratio',
 'Area Skeleton mm 2',
 'Circularity Filled',
 'Circularity Holes',
 'Centroid X mm',
 'Centroid Y mm',
 'Coeff of variation pixel intensity',
 'Convex Area mm 2',
 'Convex Perimeter mm',
 'Centroid Distance mm',
 'Centroid Distance Area Holes Ratio',
 'Elongation',
 'Eccentricity',
 'Extent',
 'Feret Area Filled Ratio',
 'Feret Area Holes Ratio',
 'Fractal Dimension',
 'Height mm',
 'Integrated Density',
 'Intensity Max',
 'Intensity Min',
 'Intensity Mean',
 'Intensity Range',
 'Intensity Std Dev',
 'Intensity Skew',
 'Intensity Kurtosis',
 'Intensity SR',
 'Orientation deg',
 'Perim Filled Feret Ratio',
 'Perim Filled Area Filled Ratio',
 'Perim Filled Area Holes Ratio',
 'Perim Filled Major Axis Ratio',
 'Perimeter Filled mm',
 'Perimeter Holes mm',
 'Mean Position',
 'Hist Cum Slope',
 'Hist Cum 25',
 'Hist Cum 50',
 'Hist Cum 75',
 'Horiz Symmetry',
 'Vert Symmetry',
 'Weighted Centroid X',
 'Weighted Centroid Y',
 'Weighted Moment Central 00',
 'Weighted Moment Central 01',
 'Weighted Moment Central 02',
 'Weighted Moment Central 10',
 'Weighted Moment Central 11',
 'Weighted Moment Central 12',
 'Weighted Moment Central 20',
 'Weighted Moment Central 21',
 'Weighted Moment Central 22',
 'Width mm',
 'ECD mm',
 'Feret Diam mm',
 'Temp deg C',
 'Salinity',
 'Rho kg m-3',
 'Fluor',
 'Major Axis Len mm',
 'Minor Axis Len mm',
 'Pressure dbar']

